import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";

const seedData = [
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Skol (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Brahma (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Brahma puro malte (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Amstel (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Heineken (long)",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Heineken zero (long)",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Heineken (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Corona (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 8,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Corona (long)",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 9,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Budweiser (long)",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 10,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Stella (lata)",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 11,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Stella (long)",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 12,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Cervejas",
    nome: "Spaten",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 13,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Caipirinhas",
    nome: "Velho Barreiro ou 51",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Caipirinhas",
    nome: "Saquê",
    preco: 35.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Caipirinhas",
    nome: "Smirnoff ou Sky",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Caipirinhas",
    nome: "Absolut",
    preco: 45.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Caipirinhas",
    nome: "Caip.Suiça (Limão Com leite condensado)",
    preco: 45.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Gin Tônica",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Gin Tropical",
    preco: 50.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Espanhola",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Batida Cachaça",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Batida Smirnoff",
    preco: 45.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Drinks",
    nome: "Batida Absolut",
    preco: 50.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Smirnoff",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Sagatiba",
    preco: 25.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Campari",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Bacardi",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Vinho",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Gin",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Sky",
    preco: 35.0,
    descricao: "",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Doses",
    nome: "Whisky",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 8,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Sucos",
    nome: "Natural",
    preco: 25.0,
    descricao: "Abacaxi, maracujá, limão, manga, kiwi, morango",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Sucos",
    nome: "Natural com leite condensado",
    preco: 30.0,
    descricao: "Abacaxi, maracujá, limão, manga, kiwi, morango",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Refrigerantes",
    nome: "COCA-COLA (lata)",
    preco: 8.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Refrigerantes",
    nome: "GUARANÁ ANTARTICA (lata)",
    preco: 8.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Refrigerantes",
    nome: "H2O",
    preco: 12.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Energeticos",
    nome: "Red Bull",
    preco: 25.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Água Mineral",
    preco: 6.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Água com Gás",
    preco: 8.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Água de Coco",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Copo de Gelo",
    preco: 10.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Água tônica",
    preco: 10.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Balde de Gelo",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "BEBIDAS",
    subcategoria: "Águas",
    nome: "Copo de Limão com Gelo",
    preco: 15.0,
    descricao: "",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "Misto Quente",
    preco: 30.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "Bauru",
    preco: 35.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "X Burguer",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "X Salada",
    preco: 45.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "X Frango Salada",
    preco: 40.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "X Egg Salada",
    preco: 50.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Lanches",
    nome: "X Bacon Salada",
    preco: 50.0,
    descricao: "",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Sanduiche Natural",
    nome: "PEITO DE PERU",
    preco: 50.0,
    descricao: "Peito de peru, alface, cenoura, beterraba e maionese",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Sanduiche Natural",
    nome: "ATUM",
    preco: 50.0,
    descricao: "Atum com catupiry ou maionese, cenoura ralada fresca, alface e beterraba",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Sanduiche Natural",
    nome: "QUEIJO BRANCO",
    preco: 50.0,
    descricao: "Queijo branco com maionese ou catupiry e cenoura fresca ralada",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Sanduiche Natural",
    nome: "FRANGO",
    preco: 50.0,
    descricao: "Peito de frango desfiado com maionese ou catupiry, mussarela e cenoura fresca ralada",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Batata Frita",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Mandioca Frita",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Polenta Frita",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Fritas com cheddar e bacon",
    preco: 110.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Polenta com cheddar e bacon",
    preco: 110.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Cebola Empanada",
    preco: 140.0,
    descricao: "",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Frango à passarinho",
    preco: 160.0,
    descricao: "",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Isca de Frango Empanado",
    preco: 150.0,
    descricao: "",
    ativo: true,
    ordem: 8,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Calabresa acebolada",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 9,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Isca de Frango no azeite",
    preco: 150.0,
    descricao: "",
    ativo: true,
    ordem: 10,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Aperitivos",
    nome: "Contra Filé Acebolado",
    preco: 190.0,
    descricao: "",
    ativo: true,
    ordem: 11,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Bolinho de Bacalhau",
    preco: 150.0,
    descricao: "",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Mini Coxinha (24 unidades)",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Mini Kibe",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Bolinho de Queijo (24 unidades)",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Provolone à milanesa",
    preco: 100.0,
    descricao: "",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Salgados",
    nome: "Pastel Misto (24 unidades)",
    preco: 100.0,
    descricao: "Sabores de Pastel : Camarão, Carne e Queijo",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Casquinha de Siri",
    preco: 35.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Porquinho",
    preco: 180.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Pescada",
    preco: 180.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Tilápia",
    preco: 190.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Linguado",
    preco: 200.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Cação",
    preco: 200.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 6,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Filé de Abadejo",
    preco: 200.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 7,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Lula à Dorê",
    preco: 200.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 8,
  },
  {
    categoriaPrincipal: "PORÇÕES",
    subcategoria: "Frutos do Mar",
    nome: "Camarão à Dorê",
    preco: 200.0,
    descricao: "Acompanha molho rosé e limão",
    ativo: true,
    ordem: 9,
  },
  {
    categoriaPrincipal: "COMBOS",
    subcategoria: "Combos",
    nome: "COMBO MAHALO",
    preco: 320.0,
    descricao: "1 porção mista de mini salgados (36 unidades), 1 porção de fritas",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "COMBOS",
    subcategoria: "Combos",
    nome: "COMBO MAROLA",
    preco: 360.0,
    descricao: "1 porção de fritas, 1 porção de isca de frango à milanesa, 1 porção de Linguado",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "COMBOS",
    subcategoria: "Combos",
    nome: "COMBO ALOHA",
    preco: 300.0,
    descricao: "1 porção de badejo, 1 porção de fritas",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "COMBOS",
    subcategoria: "Combos",
    nome: "COMBO COSTEIRA",
    preco: 320.0,
    descricao: "1 porção de camarão, 1 porção de fritas, 2 casquinha de siri",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "COMBOS",
    subcategoria: "Combos",
    nome: "COMBO CAIÇARA",
    preco: 400.0,
    descricao: "1 porção de camarão do dia, 1 porção de filé de Linguado",
    ativo: true,
    ordem: 5,
  },

  // Recados e KITTIA NALVA
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Será cobrado a taxa de serviço 10%",
    ativo: true,
    ordem: 1,
  },
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Porções só serão servidas até as 16h",
    ativo: true,
    ordem: 2,
  },
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Não cobramos cadeiras, mas se quebrar será cobrado 180,00 cada",
    ativo: true,
    ordem: 3,
  },
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Sentar com cooler em nossas mesas será cobrado R$100,00",
    ativo: true,
    ordem: 4,
  },
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Não dividimos conta no caixa, agradecemos a compreensão",
    ativo: true,
    ordem: 5,
  },
  {
    categoriaPrincipal: "RECADOS e KIT TIA NALVA",
    subcategoria: "Avisos",
    nome: "Consumo mínimo: R$50,00 por pessoa",
    ativo: true,
    ordem: 6,
  },
];

export async function POST() {
  try {
    const { db } = await connectToDatabase();
    const productsCollection = db.collection("produtos");

    const deleteResult = await productsCollection.deleteMany({});
    console.log(`-> ${deleteResult.deletedCount} documentos excluídos.`);

    await productsCollection.insertMany(seedData);

    return NextResponse.json({
      message: "Database successfully reset and re-seeded.",
      deletedCount: deleteResult.deletedCount,
      insertedCount: seedData.length,
    });
  } catch (error) {
    console.error("Error seeding database:", error);
    return NextResponse.json(
      { error: "Failed to reset and re-seed database" },
      { status: 500 }
    );
  }
}
